// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AtmContext))]
    [Migration("20240923074438_ATM")]
    partial class ATM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Cuenta", b =>
                {
                    b.Property<int>("NumeroDeCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroDeCuenta"));

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<int>("CantidadDeIntentos")
                        .HasColumnType("int");

                    b.Property<string>("NumeroDeTarjeta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pin")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NumeroDeCuenta");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cuentas", (string)null);

                    b.HasData(
                        new
                        {
                            NumeroDeCuenta = 23042010,
                            Bloqueado = false,
                            CantidadDeIntentos = 0,
                            NumeroDeTarjeta = "4444222200008888",
                            Pin = 1234,
                            UsuarioId = new Guid("b3b6f399-4993-42de-8772-9ae8a732504d")
                        },
                        new
                        {
                            NumeroDeCuenta = 9122018,
                            Bloqueado = false,
                            CantidadDeIntentos = 0,
                            NumeroDeTarjeta = "4444222200009999",
                            Pin = 5678,
                            UsuarioId = new Guid("774b7fa6-50fd-4abc-80f7-b2000b349c23")
                        },
                        new
                        {
                            NumeroDeCuenta = 18122022,
                            Bloqueado = false,
                            CantidadDeIntentos = 0,
                            NumeroDeTarjeta = "4444333300009999",
                            Pin = 9012,
                            UsuarioId = new Guid("4c7c5b69-d92e-44c4-8524-abe0a229779a")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Operacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroDeCuenta")
                        .HasColumnType("int");

                    b.Property<double>("SaldoActual")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UltimaExtraccion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NumeroDeCuenta");

                    b.ToTable("Operaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d769e439-432b-4f36-ab37-5801c0205128"),
                            NumeroDeCuenta = 23042010,
                            SaldoActual = 800000.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 4, 44, 38, 659, DateTimeKind.Local).AddTicks(9784)
                        },
                        new
                        {
                            Id = new Guid("914ef540-7128-40a0-9ce4-e5f4389247c1"),
                            NumeroDeCuenta = 23042010,
                            SaldoActual = 500000.0,
                            UltimaExtraccion = new DateTime(2024, 9, 22, 4, 44, 38, 659, DateTimeKind.Local).AddTicks(9800)
                        },
                        new
                        {
                            Id = new Guid("d34b4d33-4b1b-49b5-872a-1205024e3301"),
                            NumeroDeCuenta = 23042010,
                            SaldoActual = 700000.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 3, 44, 38, 659, DateTimeKind.Local).AddTicks(9806)
                        },
                        new
                        {
                            Id = new Guid("ebfbd1ba-eb2e-4b75-9e1e-9fd758d3101b"),
                            NumeroDeCuenta = 23042010,
                            SaldoActual = 400000.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 3, 44, 38, 659, DateTimeKind.Local).AddTicks(9808)
                        },
                        new
                        {
                            Id = new Guid("79a3d8ae-a47b-45e0-aeab-f8fbcfd8247a"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 320000.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 4, 44, 38, 659, DateTimeKind.Local).AddTicks(9809)
                        },
                        new
                        {
                            Id = new Guid("7c12d056-424b-44b1-95fb-945b78654c0a"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 234500.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 0, 44, 38, 659, DateTimeKind.Local).AddTicks(9811)
                        },
                        new
                        {
                            Id = new Guid("2c25a244-58e1-4af5-8549-218d933d4747"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 570000.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 4, 44, 38, 659, DateTimeKind.Local).AddTicks(9812)
                        },
                        new
                        {
                            Id = new Guid("7a7c7eee-9bab-4e6c-a664-f040cc357cee"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 800023.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 4, 39, 38, 659, DateTimeKind.Local).AddTicks(9813)
                        },
                        new
                        {
                            Id = new Guid("8aeb0237-5fbc-4e39-88e6-b1cd02d07bc7"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 600230.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 4, 44, 38, 659, DateTimeKind.Local).AddTicks(9816)
                        },
                        new
                        {
                            Id = new Guid("7930faee-3412-44a1-9813-2e14f404af51"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 156500.0,
                            UltimaExtraccion = new DateTime(2024, 9, 22, 21, 44, 38, 659, DateTimeKind.Local).AddTicks(9818)
                        },
                        new
                        {
                            Id = new Guid("81733dac-cca8-4e9b-9737-121d45c65ac1"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 23000.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 4, 44, 38, 659, DateTimeKind.Local).AddTicks(9819)
                        },
                        new
                        {
                            Id = new Guid("1897f83c-dba7-4a35-86ef-64ddaaecd4b3"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 400.0,
                            UltimaExtraccion = new DateTime(2024, 9, 16, 4, 44, 38, 659, DateTimeKind.Local).AddTicks(9820)
                        },
                        new
                        {
                            Id = new Guid("7cdc0e9c-2f31-4088-93fd-b99559116728"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 267500.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 4, 44, 38, 659, DateTimeKind.Local).AddTicks(9822)
                        },
                        new
                        {
                            Id = new Guid("aa604404-dfc5-4158-91ae-598efe4d6323"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 1234300.0,
                            UltimaExtraccion = new DateTime(2024, 9, 24, 4, 44, 38, 659, DateTimeKind.Local).AddTicks(9823)
                        },
                        new
                        {
                            Id = new Guid("92812bff-0dcc-4396-9294-0bc91850946f"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 676540.0,
                            UltimaExtraccion = new DateTime(2024, 9, 21, 4, 44, 38, 659, DateTimeKind.Local).AddTicks(9824)
                        },
                        new
                        {
                            Id = new Guid("2a60cdcb-26ec-4ae4-867c-b249bed91a7a"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 120003.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 1, 44, 38, 659, DateTimeKind.Local).AddTicks(9826)
                        },
                        new
                        {
                            Id = new Guid("44940e3b-8bc8-4aae-b88a-3032a596075d"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 50329.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 0, 44, 38, 659, DateTimeKind.Local).AddTicks(9827)
                        },
                        new
                        {
                            Id = new Guid("867d78a3-dd1f-4170-a71b-945d54665411"),
                            NumeroDeCuenta = 9122018,
                            SaldoActual = 102003.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 4, 44, 38, 659, DateTimeKind.Local).AddTicks(9828)
                        },
                        new
                        {
                            Id = new Guid("77788191-ceba-4e8f-960a-62ad79d264fc"),
                            NumeroDeCuenta = 18122022,
                            SaldoActual = 0.0
                        },
                        new
                        {
                            Id = new Guid("cc130800-5f61-46c1-a031-49aaf5397089"),
                            NumeroDeCuenta = 18122022,
                            SaldoActual = 5000000.0,
                            UltimaExtraccion = new DateTime(2024, 9, 23, 4, 44, 38, 659, DateTimeKind.Local).AddTicks(9831)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreDeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3b6f399-4993-42de-8772-9ae8a732504d"),
                            NombreDeUsuario = "Pepe Argento"
                        },
                        new
                        {
                            Id = new Guid("4c7c5b69-d92e-44c4-8524-abe0a229779a"),
                            NombreDeUsuario = "Marcelo Gallardo"
                        },
                        new
                        {
                            Id = new Guid("774b7fa6-50fd-4abc-80f7-b2000b349c23"),
                            NombreDeUsuario = "Dardo Fuseneco"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cuenta", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Cuentas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Operacion", b =>
                {
                    b.HasOne("Domain.Entities.Cuenta", "Cuenta")
                        .WithMany("Operaciones")
                        .HasForeignKey("NumeroDeCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("Domain.Entities.Cuenta", b =>
                {
                    b.Navigation("Operaciones");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Cuentas");
                });
#pragma warning restore 612, 618
        }
    }
}
